name: build addon

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags: ["*"]
    branches: [ main, master, prime ]

  pull_request:
    branches: [ main, master, prime ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install pre-commit scons markdown
        sudo apt-get update -y
        sudo apt-get install -y gettext

    - name: Code checks
      run: |
        export SKIP=no-commit-to-branch
        pre-commit run --all

    - name: Building addon
      run: |
        scons
        scons pot

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packaged_addon
        path: |
          ./*.nvda-addon
          ./*.pot

  upload_release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: ["build"]
    steps:
    - uses: actions/checkout@v4

    - name: Download release files
      uses: actions/download-artifact@v4
      with:
        name: packaged_addon

    - name: List files for debugging
      run: ls -lR packaged_addon

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          packaged_addon/*.nvda-addon
          packaged_addon/*.pot
        fail_on_unmatched_files: true
        prerelease: ${{ contains(github.ref, '-') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
